FROM centos/nginx-112-centos7:20191126-2735d2a

RUN yum install -y wget nginx

RUN wget -P /usr/share/nginx/html https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.26.1-02-unix.tar.gz
