FROM centos

RUN yum install -y wget

RUN mkdir /soft
RUN mkdir -p /soft/nexus
WORKDIR /soft
RUN cd /soft
RUN wget -P /soft https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.26.1-02-unix.tar.gz
RUN tar -zxvf nexus-3.26.1-02-unix.tar.gz -C /soft/nexus
